import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";

const zenkaku = Zen_Kaku_Gothic_New({
  weight: ["400", "700"],
  style: ["normal"],
  variable: "--font-zenkaku",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zenkaku.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
